services:
  # test:
  #   image: comfy:11
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  comfy_pre:
    container_name: comfy_pre
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    image: comfy:12
    environment:
      - ENV=${ENV}
      - MALIANG_TASK_CALLBACK=${MALIANG_TASK_CALLBACK}

    volumes:
      - ../comfy_models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - ../comfyui_input/comfy_pre:/root/comfyui_info/ComfyUI/input
      - ../comfyui_output/comfy_pre:/root/comfyui_info/ComfyUI/output
    ports:
      - "9099:8188"
    command: [ "python3.10", "main.py", "--listen=0.0.0.0", "--queue_name=ExamplePromptQueue" ]
