version: '2.4'

services:
  comfy0:
    container_name: comfy_dev0
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    image: comfy:latest
    volumes:
      - .:/code
    ports:
      - "9200:8188"
    command: [ "python3.10", "main.py", "--listen" ]
  comfy1:
    container_name: comfy_dev1
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    image: comfy:latest
    volumes:
      - .:/code
    ports:
      - "9201:8188"
    command: [ "python3.10", "main.py", "--listen" ]