version: '2.4'

services:
  comfy0:
    container_name: comfy_dev0
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    image: comfy:latest
    volumes:
      - ./models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /data/filebrowser/comfyui_input/comfy_dev0:/root/comfyui_info/ComfyUI/input
      - /data/filebrowser/comfyui_output/comfy_dev0:/root/comfyui_info/ComfyUI/output
    ports:
      - "9100:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram"]
  comfy1:
    container_name: comfy_dev1
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    image: comfy:latest
    volumes:
      - ./models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /data/filebrowser/comfyui_input/comfy_dev1:/root/comfyui_info/ComfyUI/input
      - /data/filebrowser/comfyui_output/comfy_dev1:/root/comfyui_info/ComfyUI/output
    ports:
      - "9101:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram" ]
