version: '2.4'

services:
  comfy0:
    container_name: comfy0
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    image: comfy:10.02
    volumes:
      - /DATA/disk1/code/comfy_models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /DATA/disk1/filebrowser/comfyui_input/comfy0:/root/comfyui_info/ComfyUI/input
      - /DATA/disk1/filebrowser/comfyui_output/comfy0:/root/comfyui_info/ComfyUI/output
    ports:
      - "9100:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram", "--queue_name=ExamplePromptQueue" ]
  comfy1:
    container_name: comfy1
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    image: comfy:10.02
    volumes:
      - /DATA/disk1/code/comfy_models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /DATA/disk1/filebrowser/comfyui_input/comfy1:/root/comfyui_info/ComfyUI/input
      - /DATA/disk1/filebrowser/comfyui_output/comfy1:/root/comfyui_info/ComfyUI/output
    ports:
      - "9101:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram", "--queue_name=ExamplePromptQueue" ]
  comfy2:
    container_name: comfy2
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
    image: comfy:10.02
    volumes:
      - /DATA/disk1/code/comfy_models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /DATA/disk1/filebrowser/comfyui_input/comfy2:/root/comfyui_info/ComfyUI/input
      - /DATA/disk1/filebrowser/comfyui_output/comfy2:/root/comfyui_info/ComfyUI/output
    ports:
      - "9102:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram", "--queue_name=ExamplePromptQueue" ]
  comfy3:
    container_name: comfy3
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    image: comfy:10.02
    volumes:
      - /DATA/disk1/code/comfy_models:/root/comfyui_info/ComfyUI/models
      - ./custom_nodes:/root/comfyui_info/ComfyUI/custom_nodes
      - /DATA/disk1/filebrowser/comfyui_input/comfy3:/root/comfyui_info/ComfyUI/input
      - /DATA/disk1/filebrowser/comfyui_output/comfy3:/root/comfyui_info/ComfyUI/output
    ports:
      - "9103:8188"
    command: [ "python3.10", "main.py", "--listen","--highvram", "--queue_name=ExamplePromptQueue" ]
