version: '2.4'

services:
  comfy:
    container_name: comfy
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "9100:8188"
    command: ["python3", "main.py", "--highvram", "--cuda-device", "0"]
